USE [master]
GO
CREATE DATABASE [DevInfoSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DevInfoSystem', 
  FILENAME = N'C:\Users\romka\source\Developers information system\Developers information system\ContextDB\SqlQuery\.sys\DevInfoSystem.mdf' ,
  SIZE = 8192KB ,
  MAXSIZE = UNLIMITED,
  FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DevInfoSystem_log',
  FILENAME = N'C:\Users\romka\source\Developers information system\Developers information system\ContextDB\SqlQuery\.sys\DevInfoSystem_log.ldf' ,
  SIZE = 8192KB ,
  MAXSIZE = 2048GB ,
  FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DevInfoSystem] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DevInfoSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DevInfoSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DevInfoSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DevInfoSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DevInfoSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DevInfoSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [DevInfoSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DevInfoSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DevInfoSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DevInfoSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DevInfoSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DevInfoSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DevInfoSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DevInfoSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DevInfoSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DevInfoSystem] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DevInfoSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DevInfoSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DevInfoSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DevInfoSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DevInfoSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DevInfoSystem] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DevInfoSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DevInfoSystem] SET RECOVERY FULL 
GO
ALTER DATABASE [DevInfoSystem] SET  MULTI_USER 
GO
ALTER DATABASE [DevInfoSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DevInfoSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DevInfoSystem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DevInfoSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DevInfoSystem', N'ON'
GO
ALTER DATABASE [DevInfoSystem] SET QUERY_STORE = OFF
GO
